// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/2/2025, 11:09:59 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["/Users/beppone/Documents/TRAE Project/jacopo/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/beppone/Documents/TRAE Project/jacopo/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/beppone/Documents/TRAE Project/jacopo/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/beppone/Documents/TRAE Project/jacopo/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/beppone/Documents/TRAE Project/jacopo/plugins/**/*.{js,ts,mjs}","/Users/beppone/Documents/TRAE Project/jacopo/composables/**/*.{js,ts,mjs}","/Users/beppone/Documents/TRAE Project/jacopo/utils/**/*.{js,ts,mjs}","/Users/beppone/Documents/TRAE Project/jacopo/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/beppone/Documents/TRAE Project/jacopo/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/beppone/Documents/TRAE Project/jacopo/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/beppone/Documents/TRAE Project/jacopo/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;